import { Routes, Route, Navigate } from "react-router-dom";
import { ROUTES } from "./constants/routes";
import PageContainer from "./components/layout/PageContainer";
import ProtectedRoute from "./components/layout/ProtectedRoute";
import Intro from "./pages/Intro";
import Login from "./pages/Login";
import Dashboard from "./pages/Dashboard";
import GenericPage from "./pages/GenericPage";

const UploadData = () => (
  <GenericPage
    title="Upload Data"
    description="Upload and manage your datasets."
  />
);
const DataQuality = () => (
  <GenericPage
    title="Data Quality"
    description="Monitor and ensure the quality of your data."
  />
);
const Analytics = () => (
  <GenericPage
    title="Analytics"
    description="Advanced analytics and data exploration."
  />
);
const Forecasting = () => (
  <GenericPage
    title="Forecasting"
    description="Predictive models and time-series forecasting."
  />
);
const AIInsights = () => (
  <GenericPage
    title="AI Insights"
    description="Automated insights generated by AI."
  />
);
const Reports = () => (
  <GenericPage
    title="Reports"
    description="Generate and export custom reports."
  />
);
const Settings = () => (
  <GenericPage
    title="Settings"
    description="Manage platform settings and preferences."
  />
);

const App = () => {
  return (
    <Routes>
      <Route path={ROUTES.HOME} element={<Intro />} />
      <Route path={ROUTES.LOGIN} element={<Login />} />
      <Route element={<ProtectedRoute />}>
        <Route element={<PageContainer />}>
          <Route path={ROUTES.DASHBOARD} element={<Dashboard />} />
          <Route path={ROUTES.UPLOAD_DATA} element={<UploadData />} />
          <Route path={ROUTES.DATA_QUALITY} element={<DataQuality />} />
          <Route path={ROUTES.ANALYTICS} element={<Analytics />} />
          <Route path={ROUTES.FORECASTING} element={<Forecasting />} />
          <Route path={ROUTES.AI_INSIGHTS} element={<AIInsights />} />
          <Route path={ROUTES.REPORTS} element={<Reports />} />
          <Route path={ROUTES.SETTINGS} element={<Settings />} />
        </Route>
      </Route>
      <Route path="*" element={<Navigate to={ROUTES.HOME} replace />} />
    </Routes>
  );
};

export default App;
